### ISSUE TITLE
Achievements (double message) (BETA)

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#1034]
**Describe the bug**
Every time you get an achievement it would put it out twice, 1 with no ping and 1 with a ping
**To Reproduce**
1. get achievement nerd
2. see it twice

**Expected behavior**
only show it once

**Screenshots**
![achievement](http://felix.is-a-good-waifu.com/6YQv1fY.png)

**Comment by mount2010** [comment]
I think something is being checked twice. I couldn't reproduce the bug with the donating achievement. @Sven65 do you know why achievements would be checked and sent twice? 

This might also be on the main bot.

**Comment by Willard21** [comment]
Seems pretty obvious from a quick glance at the gwd code. `AchievementManager.checkAchievements` sends the achievement message with the ping via a RabbitMQ task, and it returns a list a achievements that the command also sends. Just delete this entire block of code
![image](https://user-images.githubusercontent.com/24826881/135450363-4703f872-f97d-4d0d-8b8f-bdfa3d7d8e1f.png)

**Comment by mount2010** [comment]
@Willard21 Thanks for your help.

I've looked through all the commands for similar functionality, and the commands which are affected by this bug are `#!donate`, `#!sell`, `#!padv`, and `#!gwd`. All of these commands still have code for sending a message with obtained achievements along with the main command text. 

In the case of `#!donate`, it checks achievements for both the receiving and sending user. However `AchievementManager.checkAchievements()` should still work for this case.

For `#!padv`, it uses `CombatCommand.addAchievementMessages`. Since `#!padv` already uses `AchievementManager.checkAchievements`, this is redundant, and we should deprecate `CombatCommand.addAchievementMessages`, and remove the tests for it.

**Comment by mount2010** [comment]
This has turned out to be more complex than expected and will take a while more.
