### ISSUE TITLE
🐛 Bug Report: Great Disturbance quest is ambiguous

### ISSUE THREAD

**Issue by Sirfirelord69** [DiscordDungeons/Bugs#1093]
### 👟 Reproduction steps

Intended path: Route B: 
1. Talk to Abigail at Amplewood Island in Aeston
Route A:
<the following for Route A is assumed until verified>
2. Gather 10 Ethernal Shards by killing Ethernals (either at Amplewood or Dimensional Gate)
3. Talk to Abigail (or maybe Arcanist)
_
Route B:
2. Travel to Dimensional Gate and Talk to Arcanist (may need 10 Ethernal Shards to be able to talk [#!adv at Dimensional Gate to gather shards])
3. Gather 10 Ethernal Shards by killing Ethernals (total of 20 shards seems like including the previous step)
4. Talk to Arcanist

with **0** shards: 
#+talk abigail
#+travel dimensional gate
#+talk arcanist

### 👍 Expected behavior

proceed to step B3 (gather 10 more shards)

### 👎 Actual Behavior

completed the quest

### 🎲 DRPG version

16.4.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

This is what I was testing for - but there seem to be 2 possible bugs, either route B is broken, or Route A Step 3 is actually the Arcanist, not Abigail. @Sven65 requesting a quest rollback, and <@193021560792154112> at this point the only thing that would help is the qst file

**Comment by AkashicBearer** [comment]
### **1. Proceed to step B3 (gather 10 more shards)**
Wether you go on to stage 3 or not all depends on the first decision you made in the quest at the start, where you chose

> You do not want to go to Ashgate? How about killing 10 Ethernals around here for me? / Ah thank you, please report your findings to an Arcanist when you have discovered something.

This decided the outcome of the quest, if u took path(1) for example, you'd end the quest at stage 2 without the reward of a Badge (Ethernal Pass). But assuming you took the path(2) then you'd continue until stage until stage 3 where you'd need to kill 10 more (which would give 10 shards) and get the badge for your extra work. 

### **2. Amount of shards**
All in all, you would need a total of 20 shards, but first 10 or the second 10 can be gathered at any time during the quest (or outside of it once there is a part 3 for the quest), and are not limited by number during the quest, meaning you could even collect 100 if you really wanted to.

**3.  Route B is broken, or Route A Step 3 is actually the Arcanist, not Abigail**
the routes arent broken, and stage 3 is the Arcanist as stated in the chosing of path 

> [...] please report your finding to an Arcanist [..]

### **4. Path Chosen**
I dont know which path you were testing, but assuming it was path 1 then its normal taht it didnt go to stage 3 since there is no stage 3 for that, it ends the quest on the 2nd stage since you arent worthy of the badge.

### **4. Quest File?**
Ill leave the [quest file](https://drive.google.com/file/d/10Yz3AcTcJIqTAqMC5uMAzBnoec8tjJoC/view?usp=sharing) with this post, though im not sure its going to help you much if even at all.

**Comment by mount2010** [comment]
Given what @AkashicBearer said, is this still an issue? @Sirfirelord69

**Comment by Sven65** [comment]
More info has not been given, closing the issue.
