### ISSUE TITLE
🐛 Bug Report: Task requested item amount can be infinity

### ISSUE THREAD

**Issue by mount2010** [DiscordDungeons/Bugs#1101]
### 👟 Reproduction steps

- Continuously decline tasks till the bug happens 

### 👍 Expected behavior

Item amounts are normal

### 👎 Actual Behavior

Item amount can be infinity with certain item types

### 🎲 DRPG version

4.16.15-beta

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Might be related to invalid item values for certain item categories causing division by 0

![image](https://user-images.githubusercontent.com/13136505/139615705-29565359-4697-4393-864b-784429437b31.png)

found by @Sirfirelord69

**Comment by Willard21** [comment]
The item that caused that was flour, which is crafted with 2 wheat. Wheat is buyable, which gives it a value of 0 for tasks (since LUX shouldn't be buyable). Originally, it would keep choosing items until it found one that had value and wasn't blacklisted. But someone just deleted the loop. SO it went from
![image](https://user-images.githubusercontent.com/24826881/139671357-ca5d1163-f2ea-4219-98fd-e1bd0f8df461.png)
to
![image](https://user-images.githubusercontent.com/24826881/139671429-b4839e90-4498-4d06-8d97-3e9f0597db03.png)

It looks like the blacklist behavior was reworked as an item property so items could be blacklisted on the fly, but there's still the issue of items with 0 value. Those could technically just be blacklisted too if you found them all, but it seems risky to rely on that.
