### ISSUE TITLE
🐛 Bug Report: #!bstop not working 

### ISSUE THREAD

**Issue by kiotashma** [DiscordDungeons/Bugs#1139]
### 👟 Reproduction steps

![image](https://user-images.githubusercontent.com/94707145/142755728-bc405fa7-4b04-46e0-9101-cfe15c5017c4.png)
![Uploading image.png…]()

### 👍 Expected behavior

it should normally stop when i use #!bstop it didnt work and said that its my turn in the battle but it still doesnt work when i do #!bfight

### 👎 Actual Behavior

wanted to battle with a friend of mine said the same thing so i came to the official drpg server and went to support to ask help but the same thing happened , Willard said to report it as a bug.

### 🎲 DRPG version

4.17.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mount2010** [comment]
Hey there,
After some investigation, this bug seems specific to you. When I tested it with my alt account bstop works as expected:
![image](https://user-images.githubusercontent.com/13136505/142762373-da8b6ca2-d770-4c64-af5b-b1065bff8aca.png)
@Sven65, can you investigate with the battle data of userid 884744786374963281 (and stop the battle since the users can't do it)? It might be an issue with old battles from before the rewrite.

**Comment by Sven65** [comment]
According to the database, that user id doesn't have a battle.

**Comment by mount2010** [comment]
I wonder what the output is if you try creating a new battle @kiotashma?

**Comment by mount2010** [comment]
See #1169 
This "bug" is probably a misunderstanding of a bad design

**Comment by Sven65** [comment]
We've changed the way the system works in the beta, and this is fixed.
