### ISSUE TITLE
🐛 Bug Report: trap error

### ISSUE THREAD

**Issue by winterbun** [DiscordDungeons/Bugs#1160]
### 👟 Reproduction steps

I planted a trap in Copperfall 8 months ago. 
Out of boredom i decided to play discordrpg for a while and checked if there's any traps i planted last time.
![image](https://user-images.githubusercontent.com/96972005/147869218-7394b655-f3ab-48ce-9831-bc75296a9338.png)

Both Silverkeep and Rivermouth don't have any problem
![image](https://user-images.githubusercontent.com/96972005/147869246-3108284e-845f-469e-bf87-0e49c0d94eae.png)

But when it came to Copperfall,
![image](https://user-images.githubusercontent.com/96972005/147869265-77d499b6-f6bd-43b3-ae6b-ad37cdbc3907.png)

### 👍 Expected behavior

There should be a trap there too ._.

### 👎 Actual Behavior

But it said there wasn't any trap planted despite saying there was a trap planted when i checked earlier.
After the error occured, it said there was no trap 
![image](https://user-images.githubusercontent.com/96972005/147869309-6ce8be4f-59be-401c-8a0d-44a4c6738300.png)

### 🎲 DRPG version

4.17.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

**Comment by FelixArgyle** [comment]
Did you use "check" on the Copperfall place two times? once before that screenshot with the error of the deadlock?

That deadlock error is an already known thing, it happens with all commands with an unknown cause to why currently, devs likely will figure something out soon enough I guess _(this is like one of the highest issues that should be focused on)_

**Comment by winterbun** [comment]
yea i did @@

**Comment by TheJustK** [comment]
This is literally what keeps on happening to me. I just started playing this game around 2 months ago and I wanted to catch something with a butterfly net (needs ball of wool) but I encountered a different bug that didn't let me use the traps so I couldn't use trap for a while. After I reported it after around 2 weeks the bug was solved and then I successfully used the trap and waited. After 1 week has passed I decided to check it but this a message popped up saying that I couldn't check my trap. So that means in this whole time that I was playing this game I couldn't catch a single thing with a trap. 

pls fix this bug I really want to craft the butterfly net.

**Comment by Willard21** [comment]
Rock is the best pet. It's strongly advised to not use #!catch ever

**Comment by TheJustK** [comment]
> Rock is the best pet. It's strongly advised to not use #!catch ever

I will still like to catch command  at least a single time

**Comment by Sven65** [comment]
Related to #1136.
