### ISSUE TITLE
🐛 Bug Report: Bot Does Not Respond 

### ISSUE THREAD

**Issue by AenonThePro** [DiscordDungeons/Bugs#1244]
### 👟 Reproduction steps

Just Play Normaly and then you will get this error randomly

### 👍 Expected behavior

It should Just Be slow or normal

### 👎 Actual Behavior

It actually makes it unplayable for a few minutes since if you try to use any command it just does not work

### 💥 Error message

The application did not respond
![image](https://user-images.githubusercontent.com/109204065/178671912-95614988-bbc2-4249-8b87-00a26070e3ff.png)
![image](https://user-images.githubusercontent.com/109204065/178674722-8d2531ef-c9ea-4e25-81b0-2456863b807b.png)

### 🎲 DRPG version

4.18.4-(Beta)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

It happens very frequenly for me but i dont know about the others

**Comment by mount2010** [comment]
Edited title as problem persists in released version

**Comment by mount2010** [comment]
Update on this issue: I've pushed an update that might resolve this problem. 
The way commands work, Discord first sends a initial request to the bot. The bot is expected to respond within 3 seconds. If we do not respond within 3 seconds, Discord interprets it as the bot not responding, and shows the "application did not respond" message. If we need more time to respond, we can send a "defer" as our initial response, and then update with the real message later. So that's what we're doing. It will hopefully get Discord to recognise that the bot is in fact working on responding.

Please try it out and let me know if the problems are resolved.

**Comment by Sven65** [comment]
This issue has been fixed in the beta.
