### ISSUE TITLE
🐛 Bug Report: Trade on Global Market for item which is unsellable / unbuyable 

### ISSUE THREAD

**Issue by Weebs666** [DiscordDungeons/Bugs#1266]
### 👟 Reproduction steps

When I was perusing the Global Market I found the following trade. 

1 Purple Blade (600G each) {ID. L8a2422p} [0 bought]

### 👍 Expected behavior

This should not be possible.

Purple Blade#26 {Lvl. 100}
It's a sword made of some purple material
Unsellable: True
Unbuyable: True
Type:          Weapon
Damage:     100 - 150

### 👎 Actual Behavior

Should not have been possible to put this up as a trade.

### 🎲 DRPG version

4.18.5

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 📝 Additional context

Prior to the slash update I would peruse the market each day basically running through gmseach type:<> and gbsearch type:<> for each of the types and I would buy / sell depending on that. Since that functionality is not available since the slash update I have been looking at the market less. As such I believe this was introduced when the slash update came in but I cannot be 100% certain of that.

**Comment by FelixArgyle** [comment]
item data has "tradable" attached as "true".  item doesn't have any set market limits however I will change it to 0-0 since it is a donator item that is unobtainable so shouldn't have trades for buying up for it. 

If you find anymore items that are found to be the same just send me a DM or ping me in the market channel is fine. 
_A fair amount of items are like this 100% I've not been through the entire item list since there are just too many items, especially old donator items that don't have "donate:true" set on their data_
