### ISSUE TITLE
One hit kill/damage issue

### ISSUE THREAD

**Issue by deadb0t** [DiscordDungeons/Bugs#186]
There has been many reports of one hit kills happening.  After testing it with a few different people I have noticed that only the static mobs are affected from level 1 to 20.  I didn't see examples of it happening after level 20 mobs.

**Comment by TopPercentageRattata** [comment]
Definitely an issue. I 1shotted 40+ mobs in a row, many of which had 300+ health, when only doing 31 to 69 damage. The issue finally stopped with this mob

% Rolled a 6
- Los​t 15 HP.
+ Dea​lt 30 HP Damage
+ Bleght deal​t 9 HP damage.
- Bleght to​ok 8 HP Da​mage.
- Bleght h​as 18/232 HP l​eft
+ Name has 446/600 HP left.
+ The en​emy Jerlp has 169/500 HP left.

Instead of being at 461, it went all the way to 169.
From then on damage was normal.

**Comment by Sven65** [comment]
Should be fixed for reals, otherwise just reopen the issue
