### ISSUE TITLE
Discord Rpg bot outputs 3x what should be outputted

### ISSUE THREAD

**Issue by Rocketduh** [DiscordDungeons/Bugs#309]
So me and my friends are using discord rpg bot, and when we do a command it does three times, so when like we use the chop command, it gives us 3x the stuff and xp. Even the adventures, when we do it we fight 3 different enemies at the same time and earn 3x the xp. When we level up we level up 3 times.

**Comment by Rocketduh** [comment]
This happened all of a sudden after one night.

**Comment by Sven65** [comment]
DM me an invite to your server at Mackan#7196

**Comment by InitialP** [comment]
I think I know what you're talking about. I will post couple of screenshots that levelled me up couple of times and created a pool of experience requirements which looks ridiculous enough. I speculate it might have something to do with xp sharing with the pet, because I'm using 50/50 ratio.
![first](https://user-images.githubusercontent.com/29098459/29730124-dd5e86bc-89d6-11e7-94f0-1213ee7c6625.PNG)
![2nd](https://user-images.githubusercontent.com/29098459/29730131-e0a67e10-89d6-11e7-83f9-15115c6e6fe7.PNG)
![3rd](https://user-images.githubusercontent.com/29098459/29730136-e36361f4-89d6-11e7-9c1b-330d7a483d1f.PNG)
![4th](https://user-images.githubusercontent.com/29098459/29730139-e6c3e288-89d6-11e7-999c-479688139115.PNG)
![5th](https://user-images.githubusercontent.com/29098459/29730144-ea63a590-89d6-11e7-8e85-c05d46f27a5f.PNG)
![6th](https://user-images.githubusercontent.com/29098459/29730150-ed83b670-89d6-11e7-95e8-de8cb2921c18.PNG)

**Comment by Rocketduh** [comment]
No no, its literally like the bot does the command three times like this 
![discordrpg](https://user-images.githubusercontent.com/31355251/29730293-a2b110e4-89ad-11e7-9c47-db8eaf3cfb8b.JPG)

**Comment by Rocketduh** [comment]
And it isn't my server, and my friend doesn't like to invite random people in..

**Comment by Sven65** [comment]
Was fixed.

**Comment by InitialP** [comment]
Would it be much to ask to fix my current xp? The gap is not expected to be like that until I get to that "wall" at 200.
