### ISSUE TITLE
After talking with Priest in #rpg-1 then trying to talk with him again as a DM to the bot

### ISSUE THREAD

**Issue by Chipp93** [DiscordDungeons/Bugs#359]
**Please describe your issue below.**  

**If an error is provided, please copy the block into the space below.**

```js

TypeError: message.channel.permissionsFor is not a function
    at Talk.prepareDialog (/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:116:24)
    at getNPCByName.then.results (/home/mackan/RPGBot/src/Commands/Commands/Locations/Talk.js:238:25)
    at <anonymous>

```

**If you have 1 screenshot or more for context of the issue, please insert into the brackets below.**  
*You may use github's standard way of presenting images, or use an image uploader (like imgur).*

![]( < image url > )

**Comment by PlayTheFallen** [comment]
@Chipp93 what exactly is the issue, we need some context so that we know why it went wrong... not just where and when

**Comment by RJain12** [comment]
![screenshot 2017-10-01 at 10 09 29 am](https://user-images.githubusercontent.com/29895437/31057030-d1866db0-a690-11e7-9623-99f54cbffe5e.png)
 It's happening everywhere, with every NPC in any location. Talking to them in a DM just outputs the error.

**Comment by PlayTheFallen** [comment]
@Chipp93 @RJain12 this happens in DMs because the DM Channel doesn't have a method for permissions **because** permissions are in guilds only...
This one came before #361 and #365 so this shall be left open unless someone finds one like this made before.

### Reference for API
- [DMChannel](https://discord.js.org/#/docs/main/11.2.0/class/DMChannel)
- [TextChannel (GuildChannel)](https://discord.js.org/#/docs/main/11.2.0/class/TextChannel?scrollTo=permissionsFor)
