### ISSUE TITLE
Death upon HP exceeding max player HP

### ISSUE THREAD

**Issue by lifeofchrome** [DiscordDungeons/Bugs#441]
_Reporting on behalf of Yuna#7288_
User died after adventuring with HP greater than max HP - not sure how that happened in the first place.
Might be a duplicate of #386 . 
![](https://cdn.discordapp.com/attachments/380093475011428353/380093817233211392/20171115_043616.JPG)
![](https://cdn.discordapp.com/attachments/380093475011428353/380093853098835968/20171115_043559.JPG)

**EDIT**
`Editor:` @PlayTheFallen
`Time:` 15:33:34 GMT+0000 (GMT Standard Time) Wed Nov 15 2017 *Generated by nodejs environment*
`Reason:` Edit link markup to render images on page.

**Comment by Sven65** [comment]
Will look into.

**Comment by shroomyun** [comment]
![kntv5he](https://user-images.githubusercontent.com/33994869/33237161-c1eb0af4-d2a6-11e7-9704-6bfb5aad40b5.jpg)
![acchevp](https://user-images.githubusercontent.com/33994869/33237162-ca294cb2-d2a6-11e7-96ab-968c491c4097.jpg)

not certain if helpful info but I try to look where extra 243HP might be. here I try #!heal auto at different channels. at the time, the bot dies at certain channels and the advised fix by others is to try at other channels/or create new ones.

**Comment by shroomyun** [comment]
update
did #!heal auto with unstable internet connection so i resend the message but it turns out it became double heal 
![_20171209_012017](https://user-images.githubusercontent.com/33994869/33777373-8133a51a-dc7f-11e7-9f6a-597608cb3726.JPG)
since this happen before, i feel i might die if i do #!adv so i thought maybe if i try to find way to shave off extra health i might not die. so i first try to use spicy candy 
![_20171209_012052](https://user-images.githubusercontent.com/33994869/33777420-b962d4ec-dc7f-11e7-9bc4-e563368952ad.JPG)
then asked for pvp 
![_20171209_012506](https://user-images.githubusercontent.com/33994869/33777485-f7764156-dc7f-11e7-9bb4-aa9cf1f99dd6.JPG)
![_20171209_012139](https://user-images.githubusercontent.com/33994869/33777497-0809ab16-dc80-11e7-8ddf-b92a5ff3995f.JPG)
![_20171209_012232](https://user-images.githubusercontent.com/33994869/33777506-1582659e-dc80-11e7-8013-249508c06141.JPG)
the thing worked and i didnt die when i did adv after ;-;
