### ISSUE TITLE
Yeti Quest-capades

### ISSUE THREAD

**Issue by Mikel-kun** [DiscordDungeons/Bugs#528]
So, what went down was plain and simple as far as the yeti questline goes;
Went to Nieves, Talked to him, Went to Blackburn Mountain, Talked to Illyena, searched, Talked to her again, Boom. Yeti.
But to my much unacquainted knowledge the yeti was far too strong! 824 damage in one hit, holy hell, but that is not the issue.
The issue is, i fled from the battle using ;adv 1. But i decided if i were to head back into the fight and constantly heal myself, i would be able to take it down.
I used the ;adv command, but i didnt get the yeti again, i got just a plain mob.
So i tried talking to Illyena again, but i got this prompt; 
{Illyena} - undefined
I have no clue what went wrong.
I just thought i'd just share my story here to make it apparent to the community.
Quest machine broke.

**Comment by Sven65** [comment]
Huh, that's very interesting, I'll look into it.

**Comment by PlayTheFallen** [comment]
@Sven65 found the issue  
[Quest Ref.](https://github.com/Sven65/RPGBot/blob/master/src/Data/Quest/Quests/ColdNorth.js#L168)  
[NPC Ref.](https://github.com/Sven65/RPGBot/blob/master/src/Data/NPC/NPCs/Illyena.js)
*`npc.noItem` is undefined, i will let you add the string to Sven65/RPGBot#81 since i don't know what it should be...*
