### ISSUE TITLE
bug on #!uset nick 

### ISSUE THREAD

**Issue by Sniperswat** [DiscordDungeons/Bugs#596]
when i do #!uset nick 2 and bug poped up and bot said "changed nickname format of Extreme_B to 2 then i did #!stats then it didnt change at all 

https://prnt.sc/ime297

**Comment by FelixArgyle** [comment]
Hey, make sure the bot has permissions to "Manage Nicknames" if that permission isn't set for the bot then it cannot change users nicknames updated with your level etc,  
NOTE: that even with this set the bot cannot change user nicknames of the server owner due to the bot having less privilege than the server owner.
![d00dbc](https://user-images.githubusercontent.com/12903523/36938263-848e65da-1f62-11e8-903d-600034ef2521.png) [needs to have this permission]

**Comment by Sniperswat** [comment]
bot has full permsissions tho

**Comment by FelixArgyle** [comment]
And are you the (server owner)? 
"NOTE: that even with this set the bot cannot change user nicknames of the server owner due to the bot having less privilege than the server owner." 
If not then make sure the bot is higher in the role list (above all users) then it can change usernames.

**Comment by Sniperswat** [comment]
im not server owner but role is on top with full permsissions and gave it to the bot

**Comment by Sven65** [comment]
If the new nickname is longer than 32 characters, it can't set the nickname.
