### ISSUE TITLE
Unicodes in Discord account name with #!uset nick 3 not functioning as intended.

### ISSUE THREAD

**Issue by loopyd** [DiscordDungeons/Bugs#637]
**Issue**:

Executing the #!uset nick 3 command to change your username to reflect your current level does not function as intended if your Discord Account nickname contains universal emoji or unicode/UTF-8 formatted characters.

**Error**:

The bot does not respond to the command.

**Images of issue**:

Figure 1:  Discord Account name containing unicodes/UTF-8:
![Figure 1](https://i.imgur.com/WD0OzE6.png)

Figure 2: How the bot reacts to this (no output, no success message)
![Figure 2](https://i.imgur.com/fe0bEU2.png)

**Comment by PlayTheFallen** [comment]
Your nickname would be longer than 32 characters *based on both your current unicode name and the setting you wish to choose*. The bot won't set your nickname simply because it is over the character limit if it were to try.

Sorry about this issue, this is something that discord themselves have decided to limit.

**Comment by loopyd** [comment]
If that's their decision i have no intent to change it  :)
Thanks for looking into it.  Its only a cosmetic bug not affecting functionality, anyhow.  Kind of did myself in choosing a long name when I registered my account in 2015. :P

**Comment by P1M5** [comment]
You know that you can change your username from the options menu and by doing so,being able to set the nick that will change as you level (Excuse me if I haven't undestood the issue)
