### ISSUE TITLE
[MEGATHREAD] Game Rules

### ISSUE THREAD

**Issue by PlayTheFallen** [DiscordDungeons/Bugs#754]
This thread is to discuss the future rules of the game. Recently, some users have tried to trick the system where we didn't already have the conditions to keep the game fair.

That said, this is to cover both core game rules and global market rules. If you have any queries about the current conditions of the game, please ask them in \#rpg-support.

**[`ADMIN NOTE`]** Any comments found to be off-topic, will be deleted with or without warning at the discretion of the moderator(s).

PS: If you want question / answer templates, I've made some myself.
I will also edit your comments to add structure to this thread.

### Question Template

```md
## Question

{{
  question
}}

## Replies
<!-- [#{n}](#issuecomment-{number}) @{user} -->
<!-- [#{n}]({permalink}) @{user} -->
- None yet...
```

### Reply Template

```md
## Replying to [comment](#issuecomment-{number})

> {{
  context
}}

## Reply

{{
  reply
}}

## Replies
<!-- [#{n}](#issuecomment-{number}) @{user} -->
<!-- [#{n}](#{permalink}) @{user} -->
- None yet
```

PS: If you don't know how to link link things correctly, just post a permalink to the post you are replying to at the top of your reply, I'll edit the rest for you. :)

**Comment by PlayTheFallen** [comment]
@Ciborn 
> Following the bans, from all possible transactions in the game, some players got, because they were abusing the market (for example), does that mean we need to **have a good sense of the amount of gold we can freely donate to another player**, and by so, making a rule, or is it only concerning the market and there is no need to make a new rule?

**On behalf of Felix Argyle#8010**
Hard to define how much you **should** be willingly allowed to donate to a certain level, and this will make toward giveaways hosted from drpg guilds be wiped with that not being allowed due to high gold donation.

Could just have a basis rule of Economy harming or such i suppose :thinking:  but guess that'll be up to Mackan on how he'd want to display that.

Hard to outline the economy far in to the game now as well.

**Comment by PlayTheFallen** [comment]
## Question

@mount2010 - [Link to comment](#issuecomment-437331572)
> What is the DD staff doing to ensure that they do not falsely ban users, and is there anything being considered that may help players that are falsely banned to disprove that they have had botted?
Does the DD staff feel that following only the graph of the player's actions (which may not be the only factor disproving an user's botting) is enough to prove that an user has had botted?

## Answer

~~**PlayTheFallen#8318 and Felix Argyle#8010**~~

~~I'd just ban and ask questions later.~~
*jokes aside*

**On behalf of Felix Argyle#8010 (direct copy)**

we do always ask eacother for when we feel slightly concerned on a graph so more than one of us are always better than a solo input.
And if 3 people feel that it's enough evidence and lines with automation then we're somewhat not looking at things wrong or different
same with users appealing if they say they don't use any automation, then it's the same.

**Comment by PlayTheFallen** [comment]
## Question

@mount2010 - [Link to comment](#issuecomment-437331572)
> What is the DD staff doing to ensure that they do not falsely ban users, and is there anything being considered that may help players that are falsely banned to disprove that they have had botted? (see comment)

## Answer

Extending Felix's answer, log filtering and time comparisons are also used to support *our* side of the argument. So even if a user were to give a completely random story or alibi, we would be able to deny such to support their side as it would clash with ours. *Even then there are some issues, but nothing is perfect.*

**Comment by mizuharamitzu** [comment]
> ## Question
> @mount2010 - [Link to comment](#issuecomment-437331572)
> 
> > What is the DD staff doing to ensure that they do not falsely ban users, and is there anything being considered that may help players that are falsely banned to disprove that they have had botted?
> > Does the DD staff feel that following only the graph of the player's actions (which may not be the only factor disproving an user's botting) is enough to prove that an user has had botted?
> 
> ## Answer
> **PlayTheFallen#8318 and Felix Argyle#8010**
> 
> I'd just ban and ask questions later (if i see a significant activity change).
> _jokes aside_
> 
> **On behalf of Felix Argyle#8010 (direct copy)**
> 
> we do always ask eacother for when we feel slightly concerned on a graph so more than one of us are always better than a solo input.
> And if 3 people feel that it's enough evidence and lines with automation then we're somewhat not looking at things wrong or different
> same with users appealing if they say they don't use any automation, then it's the same.

Sorry, I just made an account here and I might be doing this wrong. Anyway, I think the issue is that aside from the graphs, the staff does not have any other basis for the accusation. As I understand what you said, if the graph looks like an automated game play for 3 or more people, then there is no use appealing because the user is guilty for sure. I am sure though that should not be the case.

First of all, we already have useful timers like Aldebaran's which make it easy to play efficiently and like clockwork without the use of any automation tool.

Second, a person can actually stay up for hours, gaming; barely leaving the seat in front of their monitors. We can even see the most extreme cases in the news sometimes. And because the game is accessible both on computers and handheld devices, they can still play even if they do leave for dinner or "personal" breaks. I was even playing the game while walking down town, because I can and I love the game so much.

Third, the way the falsely banned users are treated breaks my heart. It's as if even if they explain to the best of their abilities how they could play so "bot-like" even without unacceptable help, what they are saying are automatically impossible and they are liars. What else can they do to be believed? Submit the CCTV camera footage of themselves for the time frame when they seem to be botting? Or as a precautionary measure, film themselves whenever they plan to use their "impossible" gaming skills to have evidence just in case they get flagged?

I'm sure that there are too many cases, that's why the staff are extra careful not to fall for any pleading tricks. Also, some players tend to take the offensive right away and get into arguments with the staff, lowering their already non-existent chances of getting cleared.

So, what I suggest...

1. Can't there be a very strict first warning, at least? There are players who love their accounts enough to sacrifice their time to it instead of other things. The best you can give them back is not to erase all of their real efforts like a game with a malfunctioning save feature.

2. Set up a sort of system where the players are automatically warned when there seems to be suspicious behavior and make them do a specific task right on the spot to clear themselves. For example, you can make them unable to use the commands for 30 seconds to grab their attention, then have an automated warning message asking the player to tap/click on a reaction out of several reactions on the message if they are not a bot, like how reactions appear on quest. Then, it will be proven that there is actually a person behind the screen and just to make sure, ask them to stop for a short amount of time (let's say 5 minutes) before playing again. That should make it easier to know that they are bots if they don't stop even if the commands don't work, right?

3. Give the players more concrete figures or examples of what can get them flagged. I'm sure there are too many to count. Like, if the staff thinks it is impossible for someone to play for 20 hours straight without even missing side quests on time or anything like, let them know so they can slow down. As humans, we can ignore the timers a bit if we need to so that we won't look like we're some programmed bots without feelings.

So, there. Sorry that this is too long but I really hope this properly gets across. Thank you for the hard work on the game too...

**Comment by Sven65** [comment]
Side note to @mizuharamitzu question 2: Doing it that way would let users write their bots to handle that way of checking if they're bots.

**Comment by mizuharamitzu** [comment]
> > Sorry, I just made an account here and I might be doing this wrong. Anyway, I think the issue is that aside from the graphs, the staff does not have any other basis for the accusation. As I understand what you said, if the graph looks like an automated game play for 3 or more people, then there is no use appealing because the user is guilty for sure. I am sure though that should not be the case.
> 
> I can't speak on behalf for the whole team, but I feel it's to give users a fairly given case even if our evidence outweighs what they bring to their claim, as most do appeal there are often misconceptions with some cases where we'll look further into our logs/graphs to get a general basis of their gameplay aswell as take in-count for their stories for why their graph may look like that to them. - With this, we often reach out to other members on the team to get the right decision before giving out the options.
> 
> > Set up a sort of system where the players are automatically warned when there seems to be suspicious behavior and make them do a specific task right on the spot to clear themselves. For example, you can make them unable to use the commands for 30 seconds to grab their attention, then have an automated warning message asking the player to tap/click on a reaction out of several reactions on the message if they are not a bot, like how reactions appear on quest. Then, it will be proven that there is actually a person behind the screen and just to make sure, ask them to stop for a short amount of time (let's say 5 minutes) before playing again. That should make it easier to know that they are bots if they don't stop even if the commands don't work, right?
> 
> I feel if we were to add some sort of captcha system in place to make sure "robots"(automation / macro) aren't in use then it would really affect the game itself with unwanted things to all users who simply follow the listed rules, it would be near hard to sort that system to people that fall under that radar as we manually handle this stuff there is no automation with our banning system, and people will find ways to bypass those systems if it were with a reaction as such.
> 
> > Give the players more concrete figures or examples of what can get them flagged. I'm sure there are too many to count. Like, if the staff thinks it is impossible for someone to play for 20 hours straight without even missing side quests on time or anything like that, let them know so they can slow down. As humans, we can ignore the timers a bit if we need to so that we won't look like we're some programmed bots without feelings.
> 
> We already give enough evidence if we were to give anymore then our system could possibly be exposed and bypassable. Your argument really stands small with a user being able to play 20 hours **continously**, you'd have better / other things to do, if your saying you get up and not goto the toilet, eat , work, school, go outside then your under a really bad health risk, this is also impossible to follow the same pattern 20 hours continously, there will always be mistakes and human errors however robots do not make those type of errors unless they're programmed to do so.

Yes, I made a miss there. When I say continuously playing for that long, it's because there were actual cases and those are the most extreme, like these [https://www.ranker.com/list/8-people-who-died-playing-video-games/autumn-spragg]. I just want to make a point that people like those do exists... And what I meant by 20 hours continuously, being in the game for that long but not exactly doing everything on timer. I think people on vacation or off days can do something close to that. Like being there for straight 3 hours, doing sides on the next few, etc. But yeah, it's still a bad argument on my part. 

Going to the toilet with a phone is possible except when taking a bath... And eating while playing is possible too, especially when someone is living on their own and does not need to mind table manners. They could take a bite, then copy-paste enter while chewing. Just to make sure then, were all those who were banned had some sort of long periods of time without committing errors and not doing varied tasks which shouldn't be easy to automate? It's still a huge question for me why they can be considered bots is they at least do some not too routine tasks which bots won't do.

It's too bad that there can't be something like a captcha system then... Pardon my limited knowledge with programming and the like. If that's not possible, I hope there could still be some other solution out there. I hope I can be a programmer who knows the what-nots in games like this to suggest a more concrete solution because there are still falsely accused players out there and they are helpless...

Um, can I at least insist on a sort of limiter rule? To help the hardcore players know to not be mistaken for bots... Or would you be telling me that that would just make the automaters(?) get away with it easier?

**Comment by mount2010** [comment]
## Replying to [comment](https://github.com/DiscordDungeons/Bugs/issues/754#issuecomment-437358468)

> {{
  context
}}

## Reply

{{
  I really feel they can be treated better, through. I understand they're busy and there are very few of you and there's also a limited amount of users willing to become bot hunters, but at least, can't they be given a bit more... kindness than a simple, no, you're not going to be unbanned? At least, it is my second hand understanding that they are not very well treated.
I mean this from just an... emotive standpoint, instead of objective, but if I were an upset user who was falsely banned, I wouldn't feel that happy, definitely. I wonder if the staff now do treat these users well, despite whether they've really botted or not.
Additionally.... isn't the bot logs the *reason* for the *ban*, not the reason for denying the *appeal*? 
}}

## Replies


- None yet

**Comment by RainTheVappy** [comment]
Both for the ban and denying...?

**Comment by PlayTheFallen** [comment]
**[`ADMIN`]** This will be reopened after the release of the new guidelines.

**Comment by PlayTheFallen** [comment]
**[`ADMIN`]** Staff will have full discretion to edit and delete messages here if the topic is seen to be drifting.

**BANS WILL NOT BE DISCUSSED IN PUBLIC OR WHY WE ARE TO BAN A GIVEN USER**
Such should be discussed in private with the relevant team.
