### ISSUE TITLE
Fickle Fishing Whale Doesn't Spawn

### ISSUE THREAD

**Issue by kh9sd** [DiscordDungeons/Bugs#774]
If you go to Frostridge Shores with an adventure open, you never get the Ice Whale encounter and are forced to restart the quest.

**Comment by FelixArgyle** [comment]
**Describe the bug**
Whilst doing a quest that involves a "quest mob" if you are on a current adventure the quest mob does not appear to work,  (it should override the current adventure you are on for it to work.)

**To Reproduce**
Steps to reproduce the behavior:
1. Do a quest that involves a quest mob with an adventure in progress.
2. Proceed along with the quest until you get to a stage with a mob fight.
3. You will see that the mob will not spawn as you currently have an adventure in progress.

**Expected behavior**
For your current adventure to be overridden for the quest mob to appear.

**Version**
4.9.1

**Comment by Willard21** [comment]
I can't reproduce this. Tried with and without an adventure active, and the whale spawned both times. There's also nothing in the code that would suggest the whale wouldn't spawn for any reason.

**Comment by Saederup92** [comment]
Willard you land lubber
