### ISSUE TITLE
Unable to trade incomplete socketed items

### ISSUE THREAD

**Issue by myrissa** [DiscordDungeons/Bugs#794]
When donating an item if it does not have all sockets it will keep telling you that it didn't find the item even though it does. see attached. 
![image](https://user-images.githubusercontent.com/46257828/51766241-52094300-2097-11e9-8cf6-737dceb9c5bf.png)

User should be able to put correct item in quotes to stop the bot from trying to look for a diff name. Even tested without the # same issue. Please fix this as it is sometimes necesary to trade items that is just 2S or 2SJ etc. Also if we were able to put the "complete" name in a bracket or quotes it would resolve the issue with the bot thinking there are multiples when it comes to the 2s or +7 etc. Thanks!!!

![image](https://user-images.githubusercontent.com/46257828/51766356-94328480-2097-11e9-80dd-6e48bc3c3fcb.png)

**Comment by Willard21** [comment]
As Matthew suggested, the issue is with the 2. Some incorrect regex treats any numbers in the name as the amount, then removes them from the search. Since there's no exact matches for the item since its full name isn't checked, it treats it like a partial match and gives multiple results. Since `axe` is contained within `pickaxe`, the workaround of using the partial match (by leaving the number off) won't work as it does for other items.

`gdepitem` and `gwditem`, or passing it through the market should work (but be careful using the market since it goes public for a second).

**Comment by Willard21** [comment]
Ooooo actually, I think you can trick the regex into working if you do something like `1iron axe 2sj` so it'll cut out the `1` as the amount instead of the 2.
