### ISSUE TITLE
#!gmsell removes from the player's inventory the entirety of the specified item when placing a listing successfully

### ISSUE THREAD

**Issue by Huge-Succeeded** [DiscordDungeons/Bugs#803]
**Describe the bug.**
When placing an item for sale on the global market, the items present in the player's inventory will be set to zero.

**Steps to reproduce.**
* Place a selling trade for a certain item

* Check count of items using #!item itemname or #!inventory

* See that the total reads 0 for said item

* ~~Cry about lost cabbages~~

**Intended Behavior.**
Intended behavior would be that only the quantity of items input through the command be deducted from the user's inventory when the command is placed.

**Screenshots.**
Below are the screenshots which reflect, in order, my compass count of 188, as of 3:13pm, EST, the re-selling of 50 compasses after taking down one trade, then the attempted re-sell of 50 more compasses after removing a trade for 31 compasses, along with the 31 compasses which now grace my inventory in place of what should have been 146. (if my maths are correct)
![gmsellbug3-5](https://user-images.githubusercontent.com/37341333/52746256-1c2cef80-2faf-11e9-8fb1-502bfc0396c2.png)
![gmsellbug4-5](https://user-images.githubusercontent.com/37341333/52746274-251dc100-2faf-11e9-8d97-7ac0139044f8.png)
![gmsellbug5-5](https://user-images.githubusercontent.com/37341333/52746278-2818b180-2faf-11e9-9cb2-5e417f694558.png)

**Version**
4.8.0 (Guacamole Lizard)

**Extra notes.**
May be related to the previously filed bug relating to #!gmstop, since both bugs are related to selling listings, and my supply of maple logs, which were the contents of the erroneous trade, was also apparently 0, which I only became aware of today.

**Comment by iamJohnBrix** [comment]
I just experienced similar situation earlier. 

I have 480 iron ingot then put up 400 for sale and crafted another 460 but when I checked item irom ingot it says I dont have any iron ingot.

I'll just leave it here since idk if I should open another bug thread. Below are screenshots for proof.
![screenshot_20190214-105120](https://user-images.githubusercontent.com/47619077/52760730-83c35900-3008-11e9-80cb-27f79616ad57.png)
![screenshot_20190214-105137](https://user-images.githubusercontent.com/47619077/52760744-8c1b9400-3008-11e9-961b-bd8c876b913f.png)
![screenshot_20190214-105132](https://user-images.githubusercontent.com/47619077/52760746-8cb42a80-3008-11e9-9939-27a1e329247c.png)
![screenshot_20190214-105127](https://user-images.githubusercontent.com/47619077/52760749-8d4cc100-3008-11e9-82d0-5f465a17d544.png)
