### ISSUE TITLE
Item "War Hammer" (when it is a meta item) is Tradable

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#825]
**Describe the bug**
The Item "War Hammer" is tradable whilst it is a Meta Item.
This is due to the Original item did not have "Tradable|Untradable" tags on it at all so that needs to be added and fixed.

**To Reproduce**
1. Upgrade/Enchant War Hammer
2. Deposit it or Trade it to a user.

**Expected behavior**
Expect that it becomes untradable as Meta Items should be "Untradable"
**Screenshots**
 
![6jB9tE7](https://user-images.githubusercontent.com/12903523/59562051-b2a71580-9062-11e9-9045-9482cb78131f.png)

**Version**
4.11.2

**Additional context**
Should check other items in case they miss the "Tradable|Untradable" tags.

**Comment by Willard21** [comment]
Meta items weren't given an `untradable` tag. They just can't be `idonate`d or traded on the market.

**Comment by Sven65** [comment]
Are you able to donate it, despite it not having the tag?

**Comment by Willard21** [comment]
Nope

**Comment by FelixArgyle** [comment]
You can via "Depositing" & "Withdrawing" through using those guild commands, which still needs to be fixed and is a way of "Trading"  between Users.

**Comment by Willard21** [comment]
I assumed that was intentional since it was more work to manually disable idonate and market than it would have been to just make them `untradable`. There's no line between allowing collaboration and leaving room for exploitation. We'd also have to disable the `#!donate` command if we *really* didn't want anybody helping newer players get upgraded weapons, since you can just donate them the gold to upgrade it themselves.

**Comment by Sven65** [comment]
The `#!gdepitem` and `#!gwditem` issues with meta items are fixed now.
