### ISSUE TITLE
Travel bug, possibly a party bug

### ISSUE THREAD

**Issue by Makkurokuroe** [DiscordDungeons/Bugs#826]
**Describe the bug**
After using the travel command the bot replied that I couldn't travel in a party, obviously I wasn't in one. After checking with the party command and the bot replied that I wasn't in any party, the next travel command worked normally.

**To Reproduce**
Use the travel command.

**Expected behavior**
I expected to start travelling.

**Screenshots**
![image](https://cdn.discordapp.com/attachments/420980314194575363/589993699815981078/Screenshot_2019-06-17-03-14-48.png)

**Version**
June 17th 2019

**Additional context**
I only do skills and adv everyday, the only odd thing I did before the bug appeared was joining a guild.
Also I play on chiaki server, there they use a different prefix for commands, its "." instead of "#!".

**Comment by Sven65** [comment]
Sounds like the party command doesn't reset the leave state properly.

**Comment by Willard21** [comment]
Dungeon has/had the same problem. Depending on how you exited the party, your party data will either be set to `""` or `null`. Doing `#!party` with no party will set it to null, which "fixes" it, but really we just need to always check for all falsy values (`!userData.party`) instead of only checking for `null` and `undefined`.
