### ISSUE TITLE
Adventuring at altars

### ISSUE THREAD

**Issue by Infonioknight** [DiscordDungeons/Bugs#921]
It isn't supposed to be possible to adventure in altars but after the new bot update, it's possible to adventure at the caeli altar.

**Comment by Sven65** [comment]
Please follow the issue template next time you create an issue.
What version is the bug in?

**Comment by FelixArgyle** [comment]
**Describe the bug**
You can adventure in Location: Caeli Altar (all altars are meant to be a non-adventure zone)


**Steps to reproduce the behavior:**
Travel to Caeli Altar and `#!adv`
**Expected behavior**
To have Adventure disabled in the location

**Version**
4.14 (was when the issue took place from Infonioknight's post)

**Comment by Sven65** [comment]
This has been fixed in some version.
