### ISSUE TITLE
guild names not supporting all the utf's

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#928]
**Describe the bug**
User had their guild not working due to the name
Old name: DRACHENZÄHMER 
New name: DRACHENNEST
new name fixed the issue, but it should support the old name no matter what.
**To Reproduce**
1. change guild name to "DRACHENZÄHMER" or anything with "Ä" used in
2. use `#!guild` or `#!guild name` (it will not work no matter what)

**Expected behavior**
Expect it to support all the utf's
**Screenshots**
![1002](http://felix-argyle.is-into.men/H3v8EkL.png)
![1002](http://felix-argyle.is-into.men/12La5gM.png)

**Version**
 4.14.8

**Comment by Willard21** [comment]
This is caused by RethinkDB's `downcase` function not properly setting non-ASCII characters to lowercase to do the string comparison. As a result, uppercase non-ASCII characters can't be matched. A workaround is to only use lowercase characters where accents are needed, or to only use ASCII (non accented) letters.

**Comment by Sven65** [comment]
According to the [RethinkDB Docs](https://rethinkdb.com/api/javascript/upcase), the `upcase` and `downcase` functions only affects ASCII chars.

One workaround is to run it as `r.db().table().filter(r.js("(function(row){ return row.name.toUpperCase() === 'DRACHENZÄHMER'})"))`, but this is rather slow.

**Comment by Sven65** [comment]
It looks like we might be able to use [regex](https://rethinkdb.com/api/javascript/match/) for searching, I'll have a look.
