### ISSUE TITLE
Level in adventure incorrect

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#945]
**Describe the bug**
The level shown in a users adventure is their incorrect level
**To Reproduce**
1. Tell Tacca to adventure and kill a mob
 - you'll see that their level is displayed incorrectly
**Expected behavior**
For the level to be shown correctly.
**Screenshots**
![taccaadv](http://felix-argyle.is-into.men/2r8Ty4j.png)
![taccalvl](http://felix-argyle.is-into.men/bsNYMbs.png)

**Version**
4.15.0

**Additional context**
I likely wrong but I think it's like that due to where walls got changed perhaps?

**Comment by Willard21** [comment]
This is intended behavior. Since a level progress bar only works if your xp is between 0 and 100%, it can't display any meaningful information if your xp is at -200,000% for your current level. To fix this, it calculates what your current level *should* be based on your current xp, and then displays your progress for that level instead.

I think it's preferable since in this case, it creates the illusion of leveling up in just 2,000 advs rather than the 10,000,000 it would actually take him. At least from a game design perspective. So he could still have the satisfaction of breaking down walls and seeing numbers go up in a reasonable amount of time.
