### ISSUE TITLE
Stats Error

### ISSUE THREAD

**Issue by FelixArgyle** [DiscordDungeons/Bugs#969]
**Describe the bug**
Any user that had pre-set `#!uset nick 1/2/3` *with their nickname being too long*, before the recent update(s) doing `#!stats` will throw an error showing "undefined"

**To Reproduce**
1. make sure your name is like 30 characters long and have a uset nick 1/2/3 enabled (if it was before the update)
2. do `#!stats` and see error

**Expected behavior**
To either tell the user that they will need to change to a different nick uset or to automatically set uset nick to 0 upon `#!stats`

**Screenshots**
![error message](http://senpai.pls-fuck.me/6JioVot.png)

**Version**
4.15.4 

**Additional context**
Only will affect people that had a uset nick already set before the update to change so it won't set it since a username is too long.  so it prob would error on a lot of older people

**Comment by Sven65** [comment]
Should be easy to fix.

**Comment by Sven65** [comment]
Is it a bug in the beta version?

**Comment by Willard21** [comment]
Haven't tested, but the TS rewrite removed all the `reject()`s, so it at least shouldn't report an `undefined` error. ~~But still stop closing bug reports without confirming they're fixed.~~ Half the bugs in the tracker have been closed for no reason, then duplicated months or years later because it was never fixed lol
