### ISSUE TITLE
Error while changing prefix

### ISSUE THREAD

**Issue by LyricCrayon8311** [DiscordDungeons/Bugs#998]
Here is the bug report form the bot:

TypeError: this.replace is not a function
    at String.value (/home/mackan/RPGBot/src/Util/Extenders.js:11:20)
    at Setprefix.Execute (/home/mackan/RPGBot/src/Commands/Commands/Admin/Setprefix.js:26:15)
    at module.exports (/home/mackan/RPGBot/src/Handlers/messageCreate.js:225:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by FelixArgyle** [comment]
> Here is the bug report form the bot:
> 
> TypeError: this.replace is not a function
> at String.value (/home/mackan/RPGBot/src/Util/Extenders.js:11:20)
> at Setprefix.Execute (/home/mackan/RPGBot/src/Commands/Commands/Admin/Setprefix.js:26:15)
> at module.exports (/home/mackan/RPGBot/src/Handlers/messageCreate.js:225:7)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
-------------------
Please follow the bug report template. It's there for a reason. Only having an error message, without any way of knowing how to actually reproduce it makes it very hard for us to fix the error.

If you create a new bug report, the template will be there for you to copy over to this one. Alternatively, you can create two new ones following it, one for the pet name issue, and one for the prefix issue.

Thanks.

_Originally posted by @Sven65 in https://github.com/DiscordDungeons/Bugs/issues/997#issuecomment-826556005_

**In the future please check if the same bug has been reported, we do not need multiple reports on the same bug, if there is any additional information it is best to put that in an already existing issue rather than creating a new one.**
-- close your issue since one already exists.
